import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ask me | Profile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  ViewMyQuestions,
}: Readonly<{
  children: React.ReactNode;
  ViewMyQuestions: React.ReactNode;
}>) {
  return (
    <>
      {children}
      <div>{ViewMyQuestions}</div>
    </>
  );
}
